# Generated by Django 4.0.6 on 2022-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xapth', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'details',
            },
        ),
    ]
