# Generated by Django 4.0.6 on 2022-07-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schemadetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=70)),
                ('schemename', models.CharField(max_length=70)),
                ('schemetype', models.CharField(max_length=70)),
                ('xapth', models.CharField(max_length=70)),
                ('field', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='form',
        ),
    ]
