# Generated by Django 4.0.6 on 2022-07-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_schemadetails_delete_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schemadetails',
            new_name='schemadetail',
        ),
    ]
