# Generated by Django 4.0.6 on 2022-07-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_schemadetails_schemadetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schemadetail',
            new_name='detail',
        ),
    ]
