# Generated by Django 4.0.6 on 2022-07-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_schemadetail_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detail',
            new_name='details',
        ),
    ]
