# Generated by Django 4.0.6 on 2022-07-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_detail_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='detail',
        ),
    ]
