# Generated by Django 4.0.6 on 2022-07-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_details_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='schemename',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='schemetype',
            new_name='mainxpath',
        ),
    ]
